apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    # eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/AmazonEKSLoadBalancerControllerRole
    # eks.amazonaws.com/role-arn: arn:aws:iam::691889635880:policy/AmazonEKS_AWS_Load_Balancer_Controller-20221021113129387000000001
    # eks.amazonaws.com/role-arn: arn:aws:iam::691889635880:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForElasticLoadBalancing
    eks.amazonaws.com/role-arn: arn:aws:iam::691889635880:role/eks-v2_eks_lb
